export const SET_CATEGORIES = 'SET_CATEGORIES';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const SET_SELECTED_CATEGORY_ID = 'SET_SELECTED_CATEGORY_ID';

export const SET_CHANNELS = 'SET_CHANNELS';
export const FETCH_CHANNELS = 'FETCH_CHANNELS';

export const SET_CHANNEL_INFO = 'SET_CHANNEL_INFO';
export const FETCH_CHANNEL_INFO = 'FETCH_CHANNEL_INFO';

export const SET_OPEN_CHANNEL_IDS = 'SET_OPEN_CHANNEL_IDS';

export const SET_CHANNEL_TVSHOWS = 'SET_CHANNEL_TVSHOWS';
export const FETCH_CHANNEL_TVSHOWS = 'FETCH_CHANNEL_TVSHOWS';

export const SET_DOMAINS = 'SET_DOMAINS';
export const SET_DOMAIN_NAME = 'SET_DOMAIN_NAME';
