export const SET_CATEGORIES = 'SET_CATEGORIES';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const SET_SELECTED_CATEGORY_ID = 'SET_SELECTED_CATEGORY_ID';

export const SET_CHANNELS = 'SET_CHANNELS';
export const FETCH_CHANNELS = 'FETCH_CHANNELS';

export const SET_TVSHOWS = 'SET_TVSHOWS';
export const FETCH_TVSHOWS = 'FETCH_TVSHOWS';
